import { useMemo, useState } from "react";
import type { Activity, ActivityStats } from "../types/activity";
import { isOverdue, toLocalIsoString } from "../utils/activityIndicators";

function isoDaysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return toLocalIsoString(date);
}

const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "ATV-1001",
    name: "Validar cálculo de ICMS na emissão",
    status: "concluido",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Rafael Souza",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(-20),
    plannedEnd: isoDaysFromNow(-10),
    actualStart: isoDaysFromNow(-19),
    actualEnd: isoDaysFromNow(-9),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1002",
    name: "Testar emissão em lote de notas fiscais",
    status: "execucao",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Rafael Souza",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(-5),
    plannedEnd: isoDaysFromNow(3),
    actualStart: isoDaysFromNow(-4),
    actualEnd: null,
    predecessors: ["ATV-1001"],
    retestCount: 0,
    issueCount: 1,
  },
  {
    id: "ATV-1003",
    name: "Validar cancelamento de NF-e",
    status: "bloqueado",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Leonardo Martins da Silva",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(-8),
    plannedEnd: isoDaysFromNow(-1),
    actualStart: isoDaysFromNow(-7),
    actualEnd: null,
    predecessors: ["ATV-1001"],
    retestCount: 1,
    issueCount: 2,
  },
  {
    id: "ATV-1004",
    name: "Testar exportação de XML da NF-e",
    status: "aguardando",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Rafael Souza",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(2),
    plannedEnd: isoDaysFromNow(9),
    actualStart: null,
    actualEnd: null,
    predecessors: ["ATV-1002"],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1005",
    name: "Testar baixa automática de boletos",
    status: "concluido",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Guilherme Fabretti",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(-25),
    plannedEnd: isoDaysFromNow(-15),
    actualStart: isoDaysFromNow(-24),
    actualEnd: isoDaysFromNow(-14),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1006",
    name: "Validar conciliação de PIX",
    status: "execucao",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Guilherme Fabretti",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(-3),
    plannedEnd: isoDaysFromNow(4),
    actualStart: isoDaysFromNow(-2),
    actualEnd: null,
    predecessors: ["ATV-1005"],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1007",
    name: "Testar estorno de pagamento duplicado",
    status: "liberado",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Leonardo Martins da Silva",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(1),
    plannedEnd: isoDaysFromNow(6),
    actualStart: null,
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1008",
    name: "Validar relatório de divergências",
    status: "cancelado",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Rafael Souza",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-10),
    plannedEnd: isoDaysFromNow(-2),
    actualStart: null,
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1009",
    name: "Testar integração com banco emissor",
    status: "bloqueado",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Guilherme Fabretti",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-6),
    plannedEnd: isoDaysFromNow(-1),
    actualStart: isoDaysFromNow(-5),
    actualEnd: null,
    predecessors: ["ATV-1006"],
    retestCount: 2,
    issueCount: 3,
  },
  {
    id: "ATV-1010",
    name: "Testar cadastro de cliente PJ",
    status: "concluido",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Leonardo Martins da Silva",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(-18),
    plannedEnd: isoDaysFromNow(-12),
    actualStart: isoDaysFromNow(-17),
    actualEnd: isoDaysFromNow(-11),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1011",
    name: "Testar cadastro de cliente PF",
    status: "concluido",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Leonardo Martins da Silva",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(-18),
    plannedEnd: isoDaysFromNow(-12),
    actualStart: isoDaysFromNow(-17),
    actualEnd: isoDaysFromNow(-12),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1012",
    name: "Validar upload de documentos",
    status: "execucao",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Rafael Souza",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(-2),
    plannedEnd: isoDaysFromNow(5),
    actualStart: isoDaysFromNow(-1),
    actualEnd: null,
    predecessors: ["ATV-1010"],
    retestCount: 0,
    issueCount: 1,
  },
  {
    id: "ATV-1013",
    name: "Testar assinatura eletrônica de contrato",
    status: "aguardando",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Guilherme Fabretti",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(4),
    plannedEnd: isoDaysFromNow(11),
    actualStart: null,
    actualEnd: null,
    predecessors: ["ATV-1012"],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1014",
    name: "Validar CPF/CNPJ na base da Receita",
    status: "execucao",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Leonardo Martins da Silva",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-4),
    plannedEnd: isoDaysFromNow(-1),
    actualStart: isoDaysFromNow(-3),
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1015",
    name: "Testar bloqueio de CPF/CNPJ inválido",
    status: "bloqueado",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Rafael Souza",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-9),
    plannedEnd: isoDaysFromNow(-3),
    actualStart: isoDaysFromNow(-8),
    actualEnd: null,
    predecessors: ["ATV-1014"],
    retestCount: 3,
    issueCount: 1,
  },
  {
    id: "ATV-1016",
    name: "Validar duplicidade de cadastro",
    status: "liberado",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Guilherme Fabretti",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(2),
    plannedEnd: isoDaysFromNow(8),
    actualStart: null,
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
  },
  {
    id: "ATV-1017",
    name: "Testar atualização cadastral em massa",
    status: "concluido",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Leonardo Martins da Silva",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(-22),
    plannedEnd: isoDaysFromNow(-16),
    actualStart: isoDaysFromNow(-21),
    actualEnd: isoDaysFromNow(-15),
    predecessors: [],
    retestCount: 1,
    issueCount: 0,
  },
  {
    id: "ATV-1018",
    name: "Validar notificação de boas-vindas",
    status: "aguardando",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Rafael Souza",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(6),
    plannedEnd: isoDaysFromNow(12),
    actualStart: null,
    actualEnd: null,
    predecessors: ["ATV-1013"],
    retestCount: 0,
    issueCount: 0,
  },
];

interface UseActivitiesResult {
  activities: Activity[];
  stats: ActivityStats;
}

export function useActivities(projectId: string): UseActivitiesResult {
  // O mock ainda não filtra por projeto — o parâmetro fica pronto para quando
  // os dados vierem de uma API real, escopados por projeto.
  void projectId;
  const [activities] = useState<Activity[]>(INITIAL_ACTIVITIES);

  const stats = useMemo<ActivityStats>(() => {
    let concluido = 0;
    let execucao = 0;
    let bloqueado = 0;
    let aguardando = 0;
    let atrasado = 0;
    for (const activity of activities) {
      if (activity.status === "concluido") concluido += 1;
      if (activity.status === "execucao") execucao += 1;
      if (activity.status === "bloqueado") bloqueado += 1;
      if (activity.status === "aguardando") aguardando += 1;
      if (isOverdue(activity)) atrasado += 1;
    }
    return { total: activities.length, concluido, execucao, bloqueado, aguardando, atrasado };
  }, [activities]);

  return { activities, stats };
}
