import { useMemo, useState } from "react";
import type { Activity, ActivityStats, NewActivityInput } from "../types/activity";
import { isOverdue, toLocalIsoString } from "../utils/activityIndicators";

function isoDaysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return toLocalIsoString(date);
}

// Próximo ATV-XXXX após o maior número já existente — não um contador fixo, pra nunca
// colidir se o seed crescer.
function nextActivityId(activities: Activity[]): string {
  const maxNum = activities.reduce((max, activity) => {
    const match = /^ATV-(\d+)$/.exec(activity.id);
    return match ? Math.max(max, Number(match[1])) : max;
  }, 0);
  return `ATV-${maxNum + 1}`;
}

const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "ATV-1001",
    name: "Validar cálculo de ICMS na emissão",
    status: "concluido",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Rafael Souza",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(-20),
    plannedEnd: isoDaysFromNow(-10),
    actualStart: isoDaysFromNow(-19),
    actualEnd: isoDaysFromNow(-9),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.1.1.1",
    area: "Fiscal",
    system: "SAP S/4HANA",
    transaction: "VF01",
    expectedResult: "NF-e emitida com valor de ICMS calculado conforme alíquota da operação, sem divergência frente ao SPED Fiscal.",
    notes: "Cenário validado com alíquota interna de 18%.",
    attachments: [
      { fileName: "icms_calculo_v1.pdf", sizeLabel: "180 KB", uploadedBy: "Rafael Souza", uploadedAt: isoDaysFromNow(-9) },
    ],
    approvalEvidence: {
      fileName: "icms_calculo_v1.pdf",
      sizeLabel: "180 KB",
      uploadedBy: "Rafael Souza",
      uploadedAt: isoDaysFromNow(-9),
    },
    approvalNote: "Conferido contra o SPED Fiscal, sem divergências.",
  },
  {
    id: "ATV-1002",
    name: "Testar emissão em lote de notas fiscais",
    status: "execucao",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Rafael Souza",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(-5),
    plannedEnd: isoDaysFromNow(3),
    actualStart: isoDaysFromNow(-4),
    actualEnd: null,
    predecessors: ["ATV-1001"],
    retestCount: 0,
    issueCount: 1,
    wbs: "1.1.1.2",
    area: "Fiscal",
    system: "SAP S/4HANA",
    transaction: "VF04",
    expectedResult: "Lote de notas fiscais emitido sem erros, com numeração sequencial preservada.",
    notes: "Depende da conclusão de ATV-1001 para reaproveitar a massa de dados de ICMS.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1003",
    name: "Validar cancelamento de NF-e",
    status: "bloqueado",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Leonardo Martins da Silva",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(-8),
    plannedEnd: isoDaysFromNow(-1),
    actualStart: isoDaysFromNow(-7),
    actualEnd: null,
    predecessors: ["ATV-1001"],
    retestCount: 1,
    issueCount: 2,
    wbs: "1.1.1.3",
    area: "Fiscal",
    system: "SAP S/4HANA",
    transaction: "VF11",
    expectedResult: "Nota fiscal cancelada dentro do prazo legal, com motivo de cancelamento registrado no XML.",
    notes: "Bloqueada aguardando ajuste na regra de determinação de alíquota (ver ISS-0291).",
    attachments: [
      {
        fileName: "print_erro_cancelamento.png",
        sizeLabel: "540 KB",
        uploadedBy: "Leonardo Martins da Silva",
        uploadedAt: isoDaysFromNow(-6),
      },
    ],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1004",
    name: "Testar exportação de XML da NF-e",
    status: "aguardando",
    module: "Faturamento",
    process: "Emissão de NF-e",
    tester: "Rafael Souza",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(2),
    plannedEnd: isoDaysFromNow(9),
    actualStart: null,
    actualEnd: null,
    predecessors: ["ATV-1002"],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.1.1.4",
    area: "Fiscal",
    system: "SAP S/4HANA",
    transaction: "J1B3",
    expectedResult: "Arquivo XML exportado no layout vigente da SEFAZ, sem falha de schema.",
    notes: "Aguardando conclusão de ATV-1002.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1005",
    name: "Testar baixa automática de boletos",
    status: "concluido",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Guilherme Fabretti",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(-25),
    plannedEnd: isoDaysFromNow(-15),
    actualStart: isoDaysFromNow(-24),
    actualEnd: isoDaysFromNow(-14),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.1.2.1",
    area: "Tesouraria",
    system: "SAP S/4HANA",
    transaction: "F110",
    expectedResult: "Boleto baixado automaticamente no sistema após confirmação de pagamento pelo banco.",
    notes: null,
    attachments: [
      { fileName: "boleto_baixa_lote.pdf", sizeLabel: "96 KB", uploadedBy: "Guilherme Fabretti", uploadedAt: isoDaysFromNow(-14) },
    ],
    approvalEvidence: {
      fileName: "boleto_baixa_lote.pdf",
      sizeLabel: "96 KB",
      uploadedBy: "Guilherme Fabretti",
      uploadedAt: isoDaysFromNow(-14),
    },
    approvalNote: "Validado contra extrato bancário do dia.",
  },
  {
    id: "ATV-1006",
    name: "Validar conciliação de PIX",
    status: "execucao",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Guilherme Fabretti",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(-3),
    plannedEnd: isoDaysFromNow(4),
    actualStart: isoDaysFromNow(-2),
    actualEnd: null,
    predecessors: ["ATV-1005"],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.1.2.2",
    area: "Tesouraria",
    system: "SAP S/4HANA",
    transaction: "FF67",
    expectedResult: "Transação PIX conciliada automaticamente com o extrato bancário, sem lançamento manual.",
    notes: "Depende da conclusão de ATV-1005.",
    attachments: [
      {
        fileName: "conciliacao_pix_v1.xlsx",
        sizeLabel: "72 KB",
        uploadedBy: "Guilherme Fabretti",
        uploadedAt: isoDaysFromNow(-2),
      },
    ],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1007",
    name: "Testar estorno de pagamento duplicado",
    status: "liberado",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Leonardo Martins da Silva",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(1),
    plannedEnd: isoDaysFromNow(6),
    actualStart: null,
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.1.2.3",
    area: "Tesouraria",
    system: "SAP S/4HANA",
    transaction: "FCH8",
    expectedResult: "Pagamento duplicado identificado e estornado automaticamente, com notificação ao Financeiro.",
    notes: "Ainda não iniciada — aguardando liberação do ambiente de homologação.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1008",
    name: "Validar relatório de divergências",
    status: "cancelado",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Rafael Souza",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-10),
    plannedEnd: isoDaysFromNow(-2),
    actualStart: null,
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.1.2.4",
    area: "Tesouraria",
    system: "SAP S/4HANA",
    transaction: "FB03",
    expectedResult: "Relatório lista todas as divergências entre extrato bancário e lançamentos do sistema, sem falso positivo.",
    notes: "Cancelada — escopo absorvido pela nova versão do relatório de conciliação.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1009",
    name: "Testar integração com banco emissor",
    status: "bloqueado",
    module: "Faturamento",
    process: "Conciliação de Pagamentos",
    tester: "Guilherme Fabretti",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-6),
    plannedEnd: isoDaysFromNow(-1),
    actualStart: isoDaysFromNow(-5),
    actualEnd: null,
    predecessors: ["ATV-1006"],
    retestCount: 2,
    issueCount: 3,
    wbs: "1.1.2.5",
    area: "Tesouraria",
    system: "SAP S/4HANA",
    transaction: "F-28",
    expectedResult: "Arquivo de remessa CNAB 240 processado pelo banco emissor sem timeout, mesmo com mais de 500 registros.",
    notes: "Bloqueada por timeout na integração (ver ISS-0290/ISS-0294).",
    attachments: [
      { fileName: "log_timeout_cnab240.txt", sizeLabel: "12 KB", uploadedBy: "Guilherme Fabretti", uploadedAt: isoDaysFromNow(-5) },
    ],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1010",
    name: "Testar cadastro de cliente PJ",
    status: "concluido",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Leonardo Martins da Silva",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(-18),
    plannedEnd: isoDaysFromNow(-12),
    actualStart: isoDaysFromNow(-17),
    actualEnd: isoDaysFromNow(-11),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.2.1.1",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "XD01",
    expectedResult: "Cliente PJ cadastrado com validação de CNPJ na Receita Federal, sem permitir CNPJ inválido.",
    notes: null,
    attachments: [
      {
        fileName: "cadastro_pj_evidencia.png",
        sizeLabel: "310 KB",
        uploadedBy: "Leonardo Martins da Silva",
        uploadedAt: isoDaysFromNow(-11),
      },
    ],
    approvalEvidence: {
      fileName: "cadastro_pj_evidencia.png",
      sizeLabel: "310 KB",
      uploadedBy: "Leonardo Martins da Silva",
      uploadedAt: isoDaysFromNow(-11),
    },
    approvalNote: "CNPJ validado na Receita, cadastro aprovado sem ressalvas.",
  },
  {
    id: "ATV-1011",
    name: "Testar cadastro de cliente PF",
    status: "concluido",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Leonardo Martins da Silva",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(-18),
    plannedEnd: isoDaysFromNow(-12),
    actualStart: isoDaysFromNow(-17),
    actualEnd: isoDaysFromNow(-12),
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.2.1.2",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "FD01",
    expectedResult: "Cliente PF cadastrado com validação de CPF, sem permitir duplicidade de cadastro.",
    notes: null,
    attachments: [
      {
        fileName: "cadastro_pf_evidencia.png",
        sizeLabel: "280 KB",
        uploadedBy: "Leonardo Martins da Silva",
        uploadedAt: isoDaysFromNow(-12),
      },
    ],
    approvalEvidence: {
      fileName: "cadastro_pf_evidencia.png",
      sizeLabel: "280 KB",
      uploadedBy: "Leonardo Martins da Silva",
      uploadedAt: isoDaysFromNow(-12),
    },
    approvalNote: "CPF validado, sem duplicidade encontrada.",
  },
  {
    id: "ATV-1012",
    name: "Validar upload de documentos",
    status: "execucao",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Rafael Souza",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(-2),
    plannedEnd: isoDaysFromNow(5),
    actualStart: isoDaysFromNow(-1),
    actualEnd: null,
    predecessors: ["ATV-1010"],
    retestCount: 0,
    issueCount: 1,
    wbs: "1.2.1.3",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "CV01N",
    expectedResult: "Documento enviado e vinculado ao cadastro do cliente, com limite de tamanho respeitado.",
    notes: "Falha registrada para arquivos acima de 10MB (ver ISS-0298).",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1013",
    name: "Testar assinatura eletrônica de contrato",
    status: "aguardando",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Guilherme Fabretti",
    dev: "Vinícius Calefo Assarice",
    plannedStart: isoDaysFromNow(4),
    plannedEnd: isoDaysFromNow(11),
    actualStart: null,
    actualEnd: null,
    predecessors: ["ATV-1012"],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.2.1.4",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "SIGN01",
    expectedResult: "Contrato assinado eletronicamente e arquivado com trilha de validade jurídica.",
    notes: "Aguardando conclusão de ATV-1012.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1014",
    name: "Validar CPF/CNPJ na base da Receita",
    status: "execucao",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Leonardo Martins da Silva",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-4),
    plannedEnd: isoDaysFromNow(-1),
    actualStart: isoDaysFromNow(-3),
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.2.2.1",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "XD03",
    expectedResult: "Consulta à base da Receita retorna situação cadastral correta em até 3 segundos.",
    notes: null,
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1015",
    name: "Testar bloqueio de CPF/CNPJ inválido",
    status: "bloqueado",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Rafael Souza",
    dev: "M. Torres",
    plannedStart: isoDaysFromNow(-9),
    plannedEnd: isoDaysFromNow(-3),
    actualStart: isoDaysFromNow(-8),
    actualEnd: null,
    predecessors: ["ATV-1014"],
    retestCount: 3,
    issueCount: 1,
    wbs: "1.2.2.2",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "XD02",
    expectedResult: "Cadastro com CPF/CNPJ inválido é bloqueado e dispara alerta ao usuário.",
    notes: "Bloqueada — alerta não está sendo disparado (ver ISS-0293), 3º reteste em andamento.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1016",
    name: "Validar duplicidade de cadastro",
    status: "liberado",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Guilherme Fabretti",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(2),
    plannedEnd: isoDaysFromNow(8),
    actualStart: null,
    actualEnd: null,
    predecessors: [],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.2.2.3",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "XD05",
    expectedResult: "Sistema impede cadastro duplicado com o mesmo CPF/CNPJ, exibindo o registro existente.",
    notes: "Ainda não iniciada.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
  {
    id: "ATV-1017",
    name: "Testar atualização cadastral em massa",
    status: "concluido",
    module: "Cadastro de Clientes",
    process: "Validação de Dados",
    tester: "Leonardo Martins da Silva",
    dev: "C. Prado",
    plannedStart: isoDaysFromNow(-22),
    plannedEnd: isoDaysFromNow(-16),
    actualStart: isoDaysFromNow(-21),
    actualEnd: isoDaysFromNow(-15),
    predecessors: [],
    retestCount: 1,
    issueCount: 0,
    wbs: "1.2.2.4",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "XD99",
    expectedResult: "Atualização cadastral em lote processa mais de 500 registros sem travar o sistema.",
    notes: "Aprovada após 1 reteste — correção de performance validada.",
    attachments: [
      {
        fileName: "atualizacao_massa_log.xlsx",
        sizeLabel: "410 KB",
        uploadedBy: "Leonardo Martins da Silva",
        uploadedAt: isoDaysFromNow(-15),
      },
    ],
    approvalEvidence: {
      fileName: "atualizacao_massa_log.xlsx",
      sizeLabel: "410 KB",
      uploadedBy: "Leonardo Martins da Silva",
      uploadedAt: isoDaysFromNow(-15),
    },
    approvalNote: "Segunda execução processou os 500+ registros sem travamento.",
  },
  {
    id: "ATV-1018",
    name: "Validar notificação de boas-vindas",
    status: "aguardando",
    module: "Cadastro de Clientes",
    process: "Onboarding",
    tester: "Rafael Souza",
    dev: "J. Prado",
    plannedStart: isoDaysFromNow(6),
    plannedEnd: isoDaysFromNow(12),
    actualStart: null,
    actualEnd: null,
    predecessors: ["ATV-1013"],
    retestCount: 0,
    issueCount: 0,
    wbs: "1.2.1.5",
    area: "Cadastro",
    system: "SAP S/4HANA",
    transaction: "SO10",
    expectedResult: "Notificação de boas-vindas enviada uma única vez por cadastro concluído, sem duplicidade.",
    notes: "Aguardando conclusão de ATV-1013.",
    attachments: [],
    approvalEvidence: null,
    approvalNote: null,
  },
];

interface UseActivitiesResult {
  activities: Activity[];
  stats: ActivityStats;
  createActivity: (input: NewActivityInput) => void;
}

export function useActivities(projectId: string): UseActivitiesResult {
  // O mock ainda não filtra por projeto — o parâmetro fica pronto para quando
  // os dados vierem de uma API real, escopados por projeto.
  void projectId;
  const [activities, setActivities] = useState<Activity[]>(INITIAL_ACTIVITIES);

  const stats = useMemo<ActivityStats>(() => {
    let concluido = 0;
    let execucao = 0;
    let bloqueado = 0;
    let aguardando = 0;
    let atrasado = 0;
    for (const activity of activities) {
      if (activity.status === "concluido") concluido += 1;
      if (activity.status === "execucao") execucao += 1;
      if (activity.status === "bloqueado") bloqueado += 1;
      if (activity.status === "aguardando") aguardando += 1;
      if (isOverdue(activity)) atrasado += 1;
    }
    return { total: activities.length, concluido, execucao, bloqueado, aguardando, atrasado };
  }, [activities]);

  // Append direto, sem validação própria — mesma simplicidade de useProjects.addTeamMember.
  // A validação de campo obrigatório vive no modal (camada de UI).
  function createActivity(input: NewActivityInput): void {
    setActivities((prev) => {
      const newActivity: Activity = {
        id: nextActivityId(prev),
        name: input.name,
        status: input.predecessors.length > 0 ? "aguardando" : "liberado",
        module: input.module,
        process: input.process,
        tester: input.tester,
        dev: input.dev,
        plannedStart: input.plannedStart,
        plannedEnd: input.plannedEnd,
        actualStart: null,
        actualEnd: null,
        predecessors: input.predecessors,
        retestCount: 0,
        issueCount: 0,
        wbs: input.wbs,
        area: input.area,
        system: input.system,
        transaction: input.transaction,
        expectedResult: input.expectedResult,
        notes: input.notes,
        attachments: [],
        approvalEvidence: null,
        approvalNote: null,
      };
      return [...prev, newActivity];
    });
  }

  return { activities, stats, createActivity };
}
